// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	model "github.com/fgunawan1995/bcg/model"
	mock "github.com/stretchr/testify/mock"
)

// CacheDAL is an autogenerated mock type for the CacheDAL type
type CacheDAL struct {
	mock.Mock
}

// EmptyCart provides a mock function with given fields: userID
func (_m *CacheDAL) EmptyCart(userID string) {
	_m.Called(userID)
}

// GetCart provides a mock function with given fields: userID
func (_m *CacheDAL) GetCart(userID string) (model.Cart, error) {
	ret := _m.Called(userID)

	var r0 model.Cart
	if rf, ok := ret.Get(0).(func(string) model.Cart); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(model.Cart)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveCart provides a mock function with given fields: userID, cart
func (_m *CacheDAL) SaveCart(userID string, cart model.Cart) {
	_m.Called(userID, cart)
}
