// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	model "github.com/fgunawan1995/bcg/model"
	mock "github.com/stretchr/testify/mock"
)

// Common is an autogenerated mock type for the Common type
type Common struct {
	mock.Mock
}

// GetPromoMappedByItemID provides a mock function with given fields: itemIDs
func (_m *Common) GetPromoMappedByItemID(itemIDs []string) (map[string]*model.Promo, error) {
	ret := _m.Called(itemIDs)

	var r0 map[string]*model.Promo
	if rf, ok := ret.Get(0).(func([]string) map[string]*model.Promo); ok {
		r0 = rf(itemIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.Promo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(itemIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
